export const C = {
  bg:       '#FBF5EC',
  bgAlt:    '#F6EEDF',
  ct:       '#FFF9EE',
  card:     '#FFFFFF',
  peach:    '#F8D9C2',
  peachD:   '#F2BFA0',
  butter:   '#F5E5BD',
  sage:     '#D9E5CF',
  sageD:    '#BCCFAE',
  lavender: '#E5DBF0',
  blush:    '#F4C9C4',
  ink:      '#2B2520',
  inkS:     '#5C5048',
  muted:    '#A1958A',
  hair:     '#EFE5D2',
  ok:       '#4A7C56',
  warn:     '#C97A3D',
  danger:   '#B5524C',
} as const;
